initial install fix; typo

diff --git a/bin/demo b/bin/demo
--- a/bin/demo
+++ b/bin/demo
@@ -1,6 +1,14 @@
 #!/bin/bash
 # Source https://github.com/cadorn/bash.origin
-. "$HOME/bash.origin"
+if [ ! -f "$HOME/.bash.origin" ]; then
+	if [ -f "bin/install" ]; then
+		bin/install
+	else
+		echo "ERROR: Run 'bin/install' first to install 'bash.origin'!"
+		exit 1;
+	fi
+fi
+. "$HOME/.bash.origin"
 function init {
 	eval BO_SELF_BASH_SOURCE="$BO_READ_SELF_BASH_SOURCE"
 	BO_deriveSelfDir ___TMP___ "$BO_SELF_BASH_SOURCE"
diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,6 +1,14 @@
 #!/bin/bash
 # Source https://github.com/cadorn/bash.origin
-. "$HOME/bash.origin"
+if [ ! -f "$HOME/.bash.origin" ]; then
+	if [ -f "bin/install" ]; then
+		bin/install
+	else
+		echo "ERROR: Run 'bin/install' first to install 'bash.origin'!"
+		exit 1;
+	fi
+fi
+. "$HOME/.bash.origin"
 function init {
 	eval BO_SELF_BASH_SOURCE="$BO_READ_SELF_BASH_SOURCE"
 	BO_deriveSelfDir ___TMP___ "$BO_SELF_BASH_SOURCE"
@@ -22,7 +30,7 @@ function init {
 		format "HEADER" "Running Tests"
 		pushd "$__BO_DIR__"
 			# TODO: Add more tests/demos into sequence.
-			./demos
+			./demo
 			# TODO: Ensure demos fail early if any of the demos fail.
 			# TODO: Look for 'DEMOS DONE' on last line to determine if success.
 		popd
